### ISSUE TITLE
Could you tag the current state?

### ISSUE THREAD

**Issue by lindig** [juergenhoetzel/ocaml-systemd#3]
It seems that the current state is quite stable. Could you tag or release it? We are currently downloading the HEAD of branch `master` but this is of course not a stable reference. Of course, we could clone this repository and add the tag ourselves but we prefer if you had a release that we could refer to.

**Comment by juergenhoetzel** [comment]
I just added a `stable` tag. I will make a new release when incorporating major changes (I thought of async journaling like [go-systemd](https://github.com/coreos/go-systemd/blob/master/journal/journal.go))

**Comment by gaborigloi** [comment]
@juergenhoetzel Hi, thanks a lot for maintaining this package! :smile: We use & depend on it in our opam repository ([xs-opam](https://github.com/xapi-project/xs-opam)). Recently, we decided to update our packages in the main OPAM repository to their most recent versions, our PR for removing the outdated packages has already been merged: https://github.com/ocaml/opam-repository/pull/9206. Now we're preparing our second PR that re-adds our up-to-date packages, which only work with the newest version of `ocaml-systemd` tagged with "`stable`", but I think we'll need a version tag instead of `stable`. Would it be possible to release a new version of this package? Then I'd be happy to update it in the main OPAM repo as part of our second PR.

**Comment by juergenhoetzel** [comment]
> Would it be possible to release a new version of this package?
Sure :beer: So

1. Moving *stable* to head of *master*
2. Update *version* to 1.2 

will fix your issues?

**Comment by gaborigloi** [comment]
For us, a `1.2` version tag at the head of *master* is sufficient, we would just use the new version tag instead of `stable`. All the upstream packages are fixed to a specific version in our opam repo, and there we currently use the `stable` tag, but I think for updating this package in the main OPAM repo, we need a fixed version tag, like `1.2`.

**Comment by juergenhoetzel** [comment]
I just pushed the `1.2` tag.

**Comment by gaborigloi** [comment]
Thanks!

**Comment by gaborigloi** [comment]
Thanks for the version tag, this is our PR which updates all our packages, and also ocaml-systemd, to their latest versions: https://github.com/ocaml/opam-repository/pull/9419
